version: '3'
services:
  bot:
    build: .
    restart: always
    volumes:
      - ./:/usr/src/app
    environment:
      - CONFIG_PATH=/usr/src/app/config.json
      - COINBASE_ADVANCED_API_KEY=${COINBASE_ADVANCED_API_KEY}
      - COINBASE_ADVANCED_API_SECRET=${COINBASE_ADVANCED_API_SECRET}
      - COINBASE_ADVANCED_API_PASSPHRASE=${COINBASE_ADVANCED_API_PASSPHRASE}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}

